### ISSUE TITLE
Bo, La, Bo La

### ISSUE THREAD

**Issue by neuralfirings** [neuralfirings/JianZiPu#4]
ex: http://www.yueqiziliao.com/guqin/202046680.html > 3 lines above Section 4

<img width="38" alt="古琴谱大全_梧叶舞秋风_减字谱_古琴曲谱" src="https://user-images.githubusercontent.com/1091403/143732464-d250950e-3e92-4099-a546-3f56669ccca9.png">

**Comment by neuralfirings** [comment]
Cloned in #11

**Comment by 0DevAI** [comment]
Just curious, why don't use the font like 楷体 instead of a more handwriting style font?
